apiVersion: v1
kind: Service
metadata:
  name: techtrends-svc
  namespace:  {{ .Values.namespace.name }}

spec:
  selector: 
    app: techtrends
  ports:
    - name: http-web
      targetPort: {{ .Values.service.targetPort }}
      port: {{ .Values.service.port }}
      # nodePort: {{ .Values.service.nodePort }}
  type: {{ .Values.service.type }}

