apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends
  namespace: sandbox

spec:
  selector:
    matchLabels:
      app: techtrends
  replicas: 1
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - name: techtrends
        image: chizzydavid/techtrends:latest
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 3111
            protocol: TCP
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /healthz
            port: 3111
          initialDelaySeconds: 20
          timeoutSeconds: 20
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3111
          initialDelaySeconds: 20
          timeoutSeconds: 20
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
          requests:
            memory: 64Mi            
            cpu: 250m

