namespace:
  name: prod

replicaCount: 5

image:
  repository: chizzydavid/techtrends
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 7111
  targetPort: 3111
  protocol: TCP

resources: 
  limits:
    memory: 256Mi
    cpu: 500m
  requests:
    memory: 128Mi
    cpu: 350m


containerPort: 3111

livenessProbe:
  path: /healthz
  port: 3111

readinessProbe:
  path: /healthz
  port: 3111


