namespace:
  name: sandbox

replicaCount: 1

image:
  repository: chizzydavid/techtrends
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 4111
  targetPort: 3111
  nodePort: 30020
  protocol: TCP

resources: 
  limits:
    memory: 128Mi
    cpu: 500m
  requests:
    memory: 64Mi            
    cpu: 250m

containerPort: 3111

livenessProbe:
  path: /healthz
  port: 3111
readinessProbe:
  path: /healthz
  port: 3111

